# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 18:44
from __future__ import unicode_literals

from django.core import management
from django.db import migrations


def load_regions(apps, schema_editor):
    management.call_command("loaddata", "regions")


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_regions)
    ]
