# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 18:46
from __future__ import unicode_literals

from django.contrib.auth import get_user_model
from django.db import migrations


def create_superuser(apps, schema_editor):
    get_user_model().objects.create_superuser(username="admin", password="nopassword", email=None)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_load_regions'),
    ]

    operations = [
        migrations.RunPython(create_superuser)
    ]
