# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0005_es_load_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatedata',
            name='unit',
            field=models.CharField(choices=[('Degrees C', 'Degrees C'), ('Total Hours', 'Total Hours'), ('mm', 'mm')], max_length=32),
        ),
    ]
