# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 14:53
from __future__ import unicode_literals

import json

from django.conf import settings
from django.db import migrations
from elasticsearch.client import Elasticsearch


def load_es_template(apps, schema_editor):
    es = Elasticsearch(hosts=[settings.ES_URL], verify_certs=False)
    es.put_template(id="climate_data_template", body=json.dumps({
        "template": "climate_data",
        "mappings": {
            "*": {
                "properties": {
                    "measurement": {
                        "type": "double"
                    },
                    "tmax": {
                        "type": "double"
                    },
                    "tmin": {
                        "type": "double"
                    },
                    "tmean": {
                        "type": "double"
                    },
                    "tdev": {
                        "type": "double"
                    },
                    "rainfall": {
                        "type": "double"
                    },
                    "sunshine": {
                        "type": "double"
                    },
                    "region": {
                        "type": "keyword"
                    }
                }
            }
        }
    }))


class Migration(migrations.Migration):
    dependencies = [
        ('climate_data', '0006_auto_20170201_1319'),
    ]

    operations = [
        migrations.RunPython(load_es_template)
    ]
