# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 06:36
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

import common.fields


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0003_create_superuser'),
        ('climate_data', '0008_auto_20170201_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateNormalizedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tmax', common.fields.CustomFloatField(blank=True, null=True)),
                ('tmin', common.fields.CustomFloatField(blank=True, null=True)),
                ('tmean', common.fields.CustomFloatField(blank=True, null=True)),
                ('rainfall', common.fields.CustomFloatField(blank=True, null=True)),
                ('sunshine', common.fields.CustomFloatField(blank=True, null=True)),
                ('tdev', common.fields.CustomFloatField(blank=True, help_text='deviation in temperature (Max - Min)',
                                                        null=True)),
                ('record_date', models.DateField()),
                ('region',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_data',
                                   to='common.Region')),
            ],
            options={
                'verbose_name': 'Normalized Climate data',
                'verbose_name_plural': 'Normalized Climate data',
            },
        ),
    ]
